services:
  app:
    build: .
    environment:
      - SQL_DB_HOST=${SQL_DB_HOST}
      - SQL_DB_USER=${SQL_DB_USER}
      - SQL_DB_PASS=${SQL_DB_PASS}
      - SQL_DB_NAME=${SQL_DB_NAME}
      - SQL_DB_PORT=${SQL_DB_PORT}
    restart: "no"